appname: 'Community Builder'
layout: 'main'
charset: 'UTF-8'
session: 'YAML'
serializer: 'JSON'

template: 'template_toolkit'
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
  DBIC:
    default:
      schema_class: 'CommunityBuilder::Schema'
      dsn: 'dbi:SQLite:dbname=/path/to/community.db'
